# Generated by Django 4.1.5 on 2023-03-02 17:38

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customusermodel_username_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusermodel',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
