# Generated by Django 4.1.5 on 2023-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=100)),
                ("pages", models.IntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=100)),
                ("release_year", models.IntegerField()),
                ("quantity", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "image",
                    models.ImageField(
                        default="shelf/files/default/default_cover.jpeg",
                        upload_to="shelf/files/book-covers/",
                    ),
                ),
            ],
        ),
    ]
