# Generated by Django 4.1.5 on 2023-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="description",
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
