# Generated by Django 4.1.5 on 2023-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='realease_year',
            new_name='release_year',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
