# Generated by Django 4.1.5 on 2023-02-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_rename_realease_year_bookmodel_release_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='title',
        ),
    ]
