# Generated by Django 4.1.5 on 2023-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_alter_bookmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(default=None, upload_to='shelf/files/book-covers/'),
        ),
    ]
