# Generated by Django 4.1.5 on 2023-02-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_bookmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(upload_to='shelf/files/book-covers/'),
        ),
    ]
